/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'serviceInterest' : ServiceInterest,
  'message' : string,
  'phone' : string,
}
export type ServiceInterest = { 'sezServices' : null } |
  { 'gstRelated' : null } |
  { 'dgft' : null } |
  { 'stpi' : null } |
  { 'hundredPercentEOU' : null } |
  { 'incomeTaxReturn' : null } |
  { 'labourLawCompliances' : null } |
  { 'general' : null } |
  { 'payrollServices' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEnquiry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, ServiceInterest],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];